# Generated by Django 4.0.6 on 2022-09-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
